# Generated by Django 5.0.2 on 2024-03-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_user_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_year',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5'), (6, 'Year 6'), (7, 'Year 7'), (8, 'Year 8')], null=True, verbose_name='Current Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
