# Generated by Django 5.0.2 on 2024-03-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_coursecategory_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
    ]
