# Generated by Django 5.0.2 on 2024-03-30 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0006_alter_coursecategory_options'),
        ('student', '0004_remove_student_name_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_course', to='course.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_course', to='student.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
