# Generated by Django 5.0.2 on 2024-04-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together=set(),
        ),
    ]
